sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t recafe54/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true recafe54/docker-react npm run test

  