sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t recafe54/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true recafe54/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-686881856108'
  path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  